#!/bin/bash

iwconfig wlan0 mode ad-hoc
iwconfig wlan0 enc 1234567890
iwconfig wlan0 essid ITB.FX

ifconfig wlan0 10.0.2.1/24
echo 1 > /proc/sys/net/ipv4/ip_forward

iptables -t nat -A POSTROUTING -j MASQUERADE 
iptables -t nat -A PREROUTING -i wlan0 -p udp --dport 53 -j DNAT --to-destination 208.67.222.222
iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 53 -j DNAT --to-destination 208.67.222.222

/etc/init.d/dhcp3-server restart
